set nocompatible
set hidden

set number
set ruler
syntax on

set cursorline

" status line always on
set laststatus=2

set cmdheight=2

" Set encoding
set encoding=utf-8

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·
set autoindent

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
" Clear highlighted search on return
:nnoremap <CR> :nohlsearch<cr>

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=.git

" Directories for swap
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Change cursor shape in iterm2 for insert mode
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" initialize janus for other plugin loading
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Command-T config
let g:CommandTMaxHeight=30

" Leader shortcuts
map <Leader>gs  :Gstatus<CR>

" Command tweaks
command! W :w

